### ISSUE TITLE
VSCode unable to launch container

### ISSUE THREAD

**Issue by MizouziE** [madalinignisca/devcontainers#31]
When trying to launch a new container using VSCode from the `docker-compose.yml` & `.devcontainer` files cloned from this repo, I was met with the following errors:
![image](https://user-images.githubusercontent.com/90829439/174059250-2cb0fe3a-0706-4a1e-83bd-abfff20a825f.png)

I tried enabling Docker Compose V2 through the Docker Desktop app, as I thought the issue was with the use of `docker-compose` rather than `docker compose` but the problem persisted. 

Upon running the same command from my terminal it returned a `The system cannot find the file specified. ` error which made it apparent that the filename was a problem. Here we are using `.yml`, not the required `.yaml`. This was never a problem before, I am not sure why it is now, but by just changing the file ext on my local yaml file, the container was built and ran as expected.

**Comment by madalinignisca** [comment]
Renamed. Please try to use the generator instead of cloning the repo. The generator will support more and more options.
